apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0001
spec:
 capacity:
   storage: 100Mi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0001
 persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0002
spec:
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0002
 persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0003
spec:
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0003
 persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0004
spec:
 capacity:
   storage: 1Gi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0004
 persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0005
spec:
 capacity:
   storage: 2Gi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0005
 persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0006
spec:
 capacity:
   storage: 512Mi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: /openshift-gitlab/pv0006
 persistentVolumeReclaimPolicy: Recycle


